env:
  contexts:
    - name: "Default Context"
      urls:
        - "http://vulnerable-api:8081"

jobs:
  - type: passiveScan-config
    parameters:
      maxAlertsPerRule: 0

  - type: spider
    parameters:
      context: "Default Context"
      maxDuration: 5  # Увеличено время сканирования до 5 минут

  - type: activeScan
    parameters:
      context: "Default Context"
      policy: "Default Policy"
      maxDuration: 10  # До 10 минут на активное сканирование
      scanOnlyInScope: false

  - type: report
    parameters:
      template: traditional-json
      reportDir: /zap/wrk
      reportFile: report.json
      reportTitle: ZAP Scan Report
