name: Trivy Image Scan (Reusable)

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      sha:
        required: true
        type: string
      ref:
        required: true
        type: string
      run_id:
        required: true
        type: string
      image_tag: # Input for the built image tag
        required: true
        type: string
    outputs:
      trivy_reports_zip:
        description: "Path to the Trivy reports ZIP artifact"
        value: ${{ jobs.docker-build-and-trivy.outputs.trivy_reports_zip }}
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  docker-build-and-trivy:
    runs-on: ubuntu-latest
    outputs:
      trivy_reports_zip: trivy-all-reports.zip
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}

      - name: Install Trivy
        run: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo bash -s -- -b /usr/local/bin

      - name: Run Trivy Scan (SARIF Output)
        id: trivy_sarif_scan
        run: |
          trivy image --format sarif --output trivy-results.sarif --severity LOW,MEDIUM,HIGH,CRITICAL ${{ inputs.image_tag }} || true

      - name: Run Trivy Scan (Table Output)
        run: |
          trivy image --format table --severity LOW,MEDIUM,HIGH,CRITICAL ${{ inputs.image_tag }} > trivy-table-report.txt || true

      - name: Upload Trivy SARIF to Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
          category: Trivy
          checkout_path: ${{ github.workspace }}
          wait-for-processing: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the passed secret here

      - name: Archive Trivy Reports to single ZIP
        run: |
          SARIF_FILE="${{ github.workspace }}/trivy-results.sarif"
          TABLE_FILE="${{ github.workspace }}/trivy-table-report.txt"

          FILES_TO_ZIP=""
          if [ -f "$SARIF_FILE" ]; then FILES_TO_ZIP="$FILES_TO_ZIP $SARIF_FILE"; fi
          if [ -f "$TABLE_FILE" ]; then FILES_TO_ZIP="$FILES_TO_ZIP $TABLE_FILE"; fi

          TEMP_ZIP_NAME="trivy-reports-temp.zip"
          FINAL_ZIP_NAME="trivy-all-reports.zip"

          if [ -n "$FILES_TO_ZIP" ]; then
            zip -j "$TEMP_ZIP_NAME" $FILES_TO_ZIP
            echo "Created $TEMP_ZIP_NAME with the following files:"
            unzip -l "$TEMP_ZIP_NAME"
          else
            echo "No Trivy report files found to archive. Creating an empty zip file."
            touch "$TEMP_ZIP_NAME"
          fi
          mv "$TEMP_ZIP_NAME" "$FINAL_ZIP_NAME"

      - name: Upload Trivy Reports ZIP Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-all-reports
          path: trivy-all-reports.zip
          retention-days: 5
