name: OWASP ZAP DAST Scan (Reusable)

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      sha:
        required: true
        type: string
      ref:
        required: true
        type: string
      run_id:
        required: true
        type: string
    secrets:
      GHCR_PAT:
        required: true

jobs:
  zap-dast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.ref }}

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Create Docker network
        run: docker network create zap-net || true

      - name: Run vulnerable-api container
        run: |
          docker run -d --rm --network zap-net --name vulnerable-api \
            -p 8081:8081 \
            ghcr.io/pr0slittt/vulnerable-api-practika:latest
      - name: Wait for API readiness
        run: |
          for i in {1..15}; do
            if curl -s http://localhost:8081; then
              echo "API is up"
              break
            else
              echo "Waiting for API..."
              sleep 2
            fi
          done
      - name: Fix permissions for workspace folder
        run: sudo chmod -R a+w ${{ github.workspace }}

      - name: Run OWASP ZAP baseline scan manually
        run: |
          docker run --rm --network zap-net -v ${{ github.workspace }}:/zap/wrk/:rw ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://vulnerable-api:8081 \
            -r zap-report.html \
            -J zap-report.json \
            -x zap-report.xml \
            -I
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-reports # ZAP already outputs multiple files, so it's fine to keep this as is
          path: |
            zap-report.html
            zap-report.json
            zap-report.xml
          retention-days: 5
