name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  semgrep_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Semgrep Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: |
            p/python
            p/security-audit
            ./semgrep-rules
        continue-on-error: true

      - name: Upload Semgrep SARIF report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-results.sarif

  trivy_scan:
    runs-on: ubuntu-latest
    needs: semgrep_scan
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build vulnerable-api Docker image
        run: docker build -t vulnerable-api:latest .

      - name: Run Trivy Container Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: vulnerable-api:latest
          format: sarif
          output: trivy-results.sarif
          severity: HIGH,CRITICAL
          ignore-unfixed: true
        continue-on-error: true

      - name: Upload Trivy SARIF report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-results.sarif

  grype_scan:
    runs-on: ubuntu-latest
    needs: trivy_scan
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build vulnerable-api Docker image
        run: docker build -t vulnerable-api:latest .

      - name: Run Grype scan
        uses: anchore/scan-action@v3
        with:
          image: vulnerable-api:latest
          output-format: sarif
        continue-on-error: true

      - name: Upload Grype SARIF report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: grype-report
          path: grype.sarif

  zap_scan:
    runs-on: ubuntu-latest
    needs: grype_scan
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create Docker network
        uses: docker://docker
        with:
          args: network create zap-net || true

      - name: Run vulnerable-api container
        uses: docker://docker
        with:
          args: run -d --rm --network zap-net --name vulnerable-api -p 8081:8081 ghcr.io/pr0slittt/vulnerable-api-practika:latest

      - name: Wait for vulnerable-api to be ready
        uses: andstor/wait-for-http-action@v1
        with:
          url: http://localhost:8081
          timeout: 30

      - name: Run OWASP ZAP baseline scan
        uses: docker://ghcr.io/zaproxy/zaproxy:stable
        with:
          args: zap-baseline.py -t http://vulnerable-api:8081 -I --auto -r zap-report.html -J zap-report.json -x zap-report.xml -w zap-report.md

      - name: Upload ZAP reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            zap-report.html
            zap-report.json
            zap-report.xml
            zap-report.md
