name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Semgrep SAST Scan
        uses: returntocorp/semgrep-action@v1
        id: semgrep_scan
        with:
          config: |
            p/python
            p/python-web
            p/security-audit
          target: './app'
          output: '${{ github.workspace }}/semgrep-results.sarif' # Убедитесь, что это записывает в корень
          output-format: sarif

      - name: List files after Semgrep scan
        run: |
          echo "Listing files in ${{ github.workspace }}:"
          ls -l ${{ github.workspace }} # <-- КЛЮЧЕВОЙ ШАГ ОТЛАДКИ
          echo "Listing files recursively in ${{ github.workspace }}:"
          ls -lR ${{ github.workspace }} # <-- Добавлено для более глубокой проверки

      - name: Upload Semgrep SARIF results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'semgrep-results.sarif' # Ищем в корне рабочей директории
          wait-for-processing: true
          # checkout_path: удалено, так как не требуется для относительного sarif_file

      - name: Download Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo bash -s -- -b /usr/local/bin
          grype version

      - name: Run Grype SCA Scan and Save SARIF
        run: |
          # Grype будет сканировать папку 'app', а вывод SARIF будет перенаправлен в файл в корне
          grype dir:./app -o sarif > ${{ github.workspace }}/grype-results.sarif || true

      - name: List files after Grype scan
        run: |
          echo "Listing files in ${{ github.workspace }}:"
          ls -l ${{ github.workspace }} # <-- КЛЮЧЕВОЙ ШАГ ОТЛАДКИ
          echo "Listing files recursively in ${{ github.workspace }}:"
          ls -lR ${{ github.workspace }} # <-- Добавлено для более глубокой проверки

      - name: Upload SARIF results to GitHub Security tab (Grype)
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'grype-results.sarif' # Ищем в корне рабочей директории
          wait-for-processing: true
          # checkout_path: удалено, так как не требуется для относительного sarif_file
