name: DevSecOps Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  security-events: write # Требуется для Code Scanning

jobs:
  # Отдельное задание для сборки Docker-образа
  build-docker-image:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Сборка Docker-образа
        id: set-tag
        run: |
          docker build -t vulnerable-api:latest .
          echo "IMAGE_TAG=vulnerable-api:latest" >> $GITHUB_ENV
          echo "image_tag=vulnerable-api:latest" >> $GITHUB_OUTPUT # Установка вывода для других заданий
          # Этот образ будет доступен для последующих заданий

  # Задания, которые вызывают переиспользуемые рабочие процессы
  # Теперь с явным указанием репозитория и основной ветки (main/master)
  # !!! ОБЯЗАТЕЛЬНО ЗАМЕНИТЕ 'main' на 'master', если ваша основная ветка называется 'master' !!!

  semgrep-scan-job:
    needs: build-docker-image
    uses: ${{ github.repository }}/.github/workflows/reusable/semgrep_scan.yaml@main # Явная ссылка: репозиторий/путь@основная_ветка
    with:
      repository: ${{ github.repository }}
      sha: ${{ github.sha }}
      ref: ${{ github.ref }}
      run_id: ${{ github.run_id }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  grype-scan-job:
    needs: build-docker-image
    uses: ${{ github.repository }}/.github/workflows/reusable/grype_scan.yaml@main # Явная ссылка: репозиторий/путь@основная_ветка
    with:
      repository: ${{ github.repository }}
      sha: ${{ github.sha }}
      ref: ${{ github.ref }}
      run_id: ${{ github.run_id }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  checkov-scan-job:
    needs: build-docker-image
    uses: ${{ github.repository }}/.github/workflows/reusable/checkov_scan.yaml@main # Явная ссылка: репозиторий/путь@основная_ветка
    with:
      repository: ${{ github.repository }}
      sha: ${{ github.sha }}
      ref: ${{ github.ref }}
      run_id: ${{ github.run_id }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  trivy-scan-job:
    needs: build-docker-image
    uses: ${{ github.repository }}/.github/workflows/reusable/trivy_scan.yaml@main # Явная ссылка: репозиторий/путь@основная_ветка
    with:
      repository: ${{ github.repository }}
      sha: ${{ github.sha }}
      ref: ${{ github.ref }}
      run_id: ${{ github.run_id }}
      image_tag: ${{ needs.build-docker-image.outputs.image_tag }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  zap-scan-job:
    needs: build-docker-image
    uses: ${{ github.repository }}/.github/workflows/reusable/zap_scan.yaml@main # Явная ссылка: репозиторий/путь@основная_ветка
    with:
      repository: ${{ github.repository }}
      sha: ${{ github.sha }}
      ref: ${{ github.ref }}
      run_id: ${{ github.run_id }}
    secrets:
      GHCR_PAT: ${{ secrets.GHCR_PAT }}
