name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Pull vulnerable-api image
        run: |
          docker pull ghcr.io/pr0slittt/vulnerable-api-practika:latest

      - name: Run vulnerable-api container
        run: |
          docker network create zap-net || echo "Network zap-net already exists"
          docker run -d --rm --name vulnerable-api --network zap-net -p 8081:8081 ghcr.io/pr0slittt/vulnerable-api-practika:latest

      - name: Run OWASP ZAP baseline scan
        run: |
          docker run --rm --network zap-net -v "${{ github.workspace }}":/zap/wrk/:rw owasp/zap2docker-stable zap-baseline.py \
          -t http://vulnerable-api:8081 -J zap-report.json

      - name: Upload ZAP report artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.json
