name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create Docker network
        run: docker network create zap-net || true

      - name: Run vulnerable-api container
        run: |
          docker run -d --rm --network zap-net --name vulnerable-api \
            -p 8081:8081 \
            ghcr.io/pr0slittt/vulnerable-api-practika:latest

      - name: Wait for vulnerable-api to be ready
        run: |
          for i in {1..15}; do
            if curl -s http://localhost:8081; then
              echo "API is up"
              break
            else
              echo "Waiting for API..."
              sleep 2
            fi
          done

      - name: Show vulnerable-api logs
        run: docker logs vulnerable-api || echo "No logs"

      - name: Run OWASP ZAP baseline scan (игнорировать предупреждения)
        run: |
          docker pull ghcr.io/zaproxy/zaproxy:stable
          # ИСПРАВЛЕНО: Убран пробел после символа продолжения строки '\' перед '--user 0'
          docker run --rm --network zap-net \
          --user 0 \
          -v "/home/runner/work/vulnerable-api-practika/vulnerable-api-practika":/zap/wrk:rw \
          -v "/home/runner/work/vulnerable-api-practika/vulnerable-api-practika/zap-rules:/zap/scripts/:ro" \
          ghcr.io/zaproxy/zaproxy:stable \
          zap-baseline.py -t http://vulnerable-api:8081 -I \
          -r zap-report.html -J zap-report.json -x zap-report.xml

      - name: Upload ZAP scan reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            zap-report.html
            zap-report.json
            zap-report.xml
