name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Semgrep SAST Scan
        uses: returntocorp/semgrep-action@v1
        id: semgrep_scan
        with:
          config: |
            p/python
            p/security-audit
          args: >-
            --target ./app
            --output semgrep-results.sarif
            --output-format sarif
        continue-on-error: true

      - name: List files after Semgrep scan
        run: |
          echo "Listing files in ${{ github.workspace }}:"
          ls -l ${{ github.workspace }}
          echo "Listing files recursively in ${{ github.workspace }}:"
          ls -lR ${{ github.workspace }}
          if [ -f "${{ github.workspace }}/semgrep-results.sarif" ]; then
            echo "semgrep-results.sarif content (first 100 lines):"
            head -n 100 "${{ github.workspace }}/semgrep-results.sarif"
          else
            echo "semgrep-results.sarif not found after scan."
          fi

      - name: Upload Semgrep SARIF results to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'semgrep-results.sarif'
          wait-for-processing: true

      - name: Download Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo bash -s -- -b /usr/local/bin
          grype version

      - name: Run Grype SCA Scan and Save SARIF
        run: |
          grype dir:./app -o sarif --file "${{ github.workspace }}/grype-results.sarif" || true

      - name: Upload SARIF results to GitHub Security tab (Grype)
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'grype-results.sarif'
          wait-for-processing: true
