name: DevSecOps Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  security-events: write

jobs:
  semgrep-sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies and jq
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update && sudo apt-get install -y jq # Устанавливаем jq
      - name: Install Semgrep CLI
        run: |
          pip install "semgrep>=1.76.0"
          semgrep --version

      # Запуск Semgrep для SARIF (для GitHub Code Scanning)
      - name: Run Semgrep SAST Scan (SARIF Output)
        id: semgrep_sarif_scan
        run: |
          SARIF_OUTPUT_PATH="${{ github.workspace }}/semgrep-results.sarif"
          semgrep \
            --config "p/python" \
            --config "p/security-audit" \
            --config "semgrep-rules/" \
            --sarif \
            -o "$SARIF_OUTPUT_PATH" \
            ./app \
            --verbose || true

      # Запуск Semgrep для JSON (для табличного отчета И для архива)
      - name: Run Semgrep SAST Scan (JSON Output)
        id: semgrep_json_scan
        run: |
          JSON_OUTPUT_PATH="${{ github.workspace }}/semgrep-results.json"
          semgrep \
            --config "p/python" \
            --config "p/security-audit" \
            --config "semgrep-rules/" \
            --json \
            -o "$JSON_OUTPUT_PATH" \
            ./app \
            --verbose || true

      # Конвертируем Semgrep JSON в табличный формат
      - name: Format Semgrep JSON to Table
        run: |
          TABLE_REPORT_PATH="${{ github.workspace }}/semgrep-table-report.txt"
          if [ -s "${{ github.workspace }}/semgrep-results.json" ]; then
            echo "Category | Rule ID | Severity | File | Line | Description" > "$TABLE_REPORT_PATH"
            echo "---------|---------|----------|------|------|-------------" >> "$TABLE_REPORT_PATH"
            jq -r '.results[] | select(.extra.severity) | "\(.extra.metadata.category // "N/A") | \(.check_id) | \(.extra.severity) | \(.path) | \(.start.line) | \(.extra.message)"' "${{ github.workspace }}/semgrep-results.json" | \
            sed 's/\n/ /g' | \
            sed 's/|/ \| /g' | \
            column -t -s '|' >> "$TABLE_REPORT_PATH"

            cat "$TABLE_REPORT_PATH" # Выводим в лог
          else
            echo "No Semgrep results found or JSON file is empty."
            echo "No Semgrep results found." > "$TABLE_REPORT_PATH"
          fi
        env:
          PYTHONUNBUFFERED: 1

      # Загружаем SARIF в Code Scanning
      - name: Upload Semgrep SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'semgrep-results.sarif'
          wait-for-processing: true

      # СОЗДАЕМ ОДИН ZIP-АРХИВ ДЛЯ ВСЕХ ОТЧЕТОВ SEMGREP
      - name: Archive Semgrep Reports to single ZIP
        run: |
          zip -j semgrep-reports.zip \
            ${{ github.workspace }}/semgrep-results.sarif \
            ${{ github.workspace }}/semgrep-results.json \
            ${{ github.workspace }}/semgrep-table-report.txt
          ls -l semgrep-reports.zip # Проверить, что файл создан

      - name: Upload Semgrep Reports ZIP Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-all-reports
          path: semgrep-reports.zip
          retention-days: 5

  grype-sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/.grype/db
          key: ${{ runner.os }}-grype-db-${{ hashFiles('grype-db-version.txt') }}
          restore-keys: ${{ runner.os }}-grype-db-

      - name: Create Grype DB Version File
        run: echo "1" > grype-db-version.txt

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/contrib/install.sh | sudo bash -s -- -b /usr/local/bin
          grype version

      # Запуск Grype для SARIF (для GitHub Code Scanning и для архива)
      - name: Run Grype SCA Scan (SARIF Output)
        id: grype_sarif_scan
        run: |
          SARIF_OUTPUT_PATH="${{ github.workspace }}/grype-results.sarif"
          grype dir:./app -o sarif --file "$SARIF_OUTPUT_PATH" || true

      # Запуск Grype для табличного отчета (для архива)
      - name: Run Grype SCA Scan (Table Output)
        run: |
          TABLE_REPORT_PATH="${{ github.workspace }}/grype-table-report.txt"
          grype dir:./app --format table > "$TABLE_REPORT_PATH"
          cat "$TABLE_REPORT_PATH"

      # Загружаем SARIF в Code Scanning
      - name: Upload Grype SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'grype-results.sarif'
          wait-for-processing: true

      # СОЗДАЕМ ОДИН ZIP-АРХИВ ДЛЯ ВСЕХ ОТЧЕТОВ GRYPE
      - name: Archive Grype Reports to single ZIP
        run: |
          zip -j grype-reports.zip \
            ${{ github.workspace }}/grype-results.sarif \
            ${{ github.workspace }}/grype-table-report.txt
          ls -l grype-reports.zip # Проверить, что файл создан

      - name: Upload Grype Reports ZIP Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: grype-all-reports
          path: grype-reports.zip
          retention-days: 5

  checkov_iac_scan:
    name: Checkov IaC Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Checkov IaC Scan (SARIF Output)
        id: checkov_sarif_scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: dockerfile,kubernetes,terraform,cloudformation,arm,ansible,serverless
          output_format: sarif
          # Checkov Action всегда создает папку, поэтому указываем путь к файлу внутри нее
          output_file_path: checkov_results.sarif/results_sarif.sarif
        # continue-on-error: true # Возможно, захотите добавить это, чтобы пайплайн не падал сразу

      - name: Run Checkov IaC Scan (CLI Output)
        run: |
          CLI_REPORT_PATH="${{ github.workspace }}/checkov-cli-report.txt"
          checkov --directory . \
                  --framework dockerfile,kubernetes,terraform,cloudformation,arm,ansible,serverless \
                  --output cli \
                  > "$CLI_REPORT_PATH" # Сохраняем консольный вывод
          cat "$CLI_REPORT_PATH"

      - name: Upload Checkov SARIF to Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov_results.sarif/results_sarif.sarif
          category: Checkov
          checkout_path: ${{ github.workspace }}
          wait-for-processing: true

      # СОЗДАЕМ ОДИН ZIP-АРХИВ ДЛЯ ВСЕХ ОТЧЕТОВ CHECKEV (SARIF и CLI)
      - name: Archive Checkov Reports to single ZIP
        run: |
          zip -j checkov-reports.zip \
            checkov_results.sarif/results_sarif.sarif \
            ${{ github.workspace }}/checkov-cli-report.txt
          ls -l checkov-reports.zip # Проверить, что файл создан

      - name: Upload Checkov Reports ZIP Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkov-all-reports
          path: checkov-reports.zip
          retention-days: 5

  docker-build-and-trivy:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        id: set-tag
        run: |
          docker build -t vulnerable-api:latest .
          echo "IMAGE_TAG=vulnerable-api:latest" >> $GITHUB_ENV

      - name: Install Trivy
        run: curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo bash -s -- -b /usr/local/bin

      # Запуск Trivy для SARIF (для GitHub Code Scanning и для архива)
      - name: Run Trivy Scan (SARIF Output)
        id: trivy_sarif_scan
        run: |
          trivy image --format sarif --output trivy-results.sarif --severity LOW,MEDIUM,HIGH,CRITICAL ${{ env.IMAGE_TAG }} || true

      # Запуск Trivy для табличного отчета (для архива)
      - name: Run Trivy Scan (Table Output)
        run: |
          trivy image --format table --severity LOW,MEDIUM,HIGH,CRITICAL ${{ env.IMAGE_TAG }} > trivy-table-report.txt

      # Загружаем SARIF в Code Scanning
      - name: Upload Trivy SARIF to Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
          category: Trivy
          checkout_path: ${{ github.workspace }}
          wait-for-processing: true

      # СОЗДАЕМ ОДИН ZIP-АРХИВ ДЛЯ ВСЕХ ОТЧЕТОВ TRIVY
      - name: Archive Trivy Reports to single ZIP
        run: |
          zip -j trivy-reports.zip \
            ${{ github.workspace }}/trivy-results.sarif \
            ${{ github.workspace }}/trivy-table-report.txt
          ls -l trivy-reports.zip # Проверить, что файл создан

      - name: Upload Trivy Reports ZIP Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-all-reports
          path: trivy-reports.zip
          retention-days: 5

  zap-dast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Create Docker network
        run: docker network create zap-net || true

      - name: Run vulnerable-api container
        run: |
          docker run -d --rm --network zap-net --name vulnerable-api \
            -p 8081:8081 \
            ghcr.io/pr0slittt/vulnerable-api-practika:latest
      - name: Wait for API readiness
        run: |
          for i in {1..15}; do
            if curl -s http://localhost:8081; then
              echo "API is up"
              break
            else
              echo "Waiting for API..."
              sleep 2
            fi
          done
      - name: Fix permissions for workspace folder
        run: sudo chmod -R a+w ${{ github.workspace }}

      - name: Run OWASP ZAP baseline scan manually
        run: |
          docker run --rm --network zap-net -v ${{ github.workspace }}:/zap/wrk/:rw ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://vulnerable-api:8081 \
            -r zap-report.html \
            -J zap-report.json \
            -x zap-report.xml \
            -I
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-reports
          path: |
            zap-report.html
            zap-report.json
            zap-report.xml
