name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Semgrep CLI
        run: |
          pip install "semgrep>=1.76.0"
          semgrep --version

      - name: Run Semgrep SAST Scan
        id: semgrep_scan_run
        run: |
          SARIF_OUTPUT_PATH="${{ github.workspace }}/semgrep-results.sarif"
          semgrep \
            --config "p/python" \
            --config "p/security-audit" \
            --config "semgrep-rules/" \
            --sarif \
            -o "$SARIF_OUTPUT_PATH" \
            ./app \
            --verbose || true
          echo "semgrep_exit_code=$?" >> "$GITHUB_OUTPUT"

      - name: Upload Semgrep SARIF results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'semgrep-results.sarif'
          wait-for-processing: true

      - name: Upload Semgrep SARIF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif-report
          path: semgrep-results.sarif
          retention-days: 5

      - name: Cache Grype DB
        uses: actions/cache@v3
        with:
          path: ~/.grype/db
          key: ${{ runner.os }}-grype-db-${{ hashFiles('grype-db-version.txt') }}
          restore-keys: |
            ${{ runner.os }}-grype-db-

      - name: Create Grype DB Version File
        run: echo "1" > grype-db-version.txt

      - name: Download Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo bash -s -- -b /usr/local/bin
          grype version

      - name: Run Grype SCA Scan and Save SARIF
        id: grype_scan_run
        run: |
          GRYPE_OUTPUT_PATH="${{ github.workspace }}/grype-results.sarif"
          grype dir:./app -o sarif --file "$GRYPE_OUTPUT_PATH" || true
          echo "grype_exit_code=$?" >> "$GITHUB_OUTPUT"

      - name: Upload Grype SARIF to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'grype-results.sarif'
          wait-for-processing: true

      - name: Upload Grype SARIF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: grype-sarif-report
          path: grype-results.sarif
          retention-days: 5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t vulnerable-api:latest .

      - name: Run Trivy Container Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'vulnerable-api:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
        continue-on-error: true

      - name: Upload Trivy SARIF results to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
          wait-for-processing: true

      - name: Upload Trivy SARIF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sarif-report
          path: trivy-results.sarif
          retention-days: 5

      - name: Run OWASP ZAP Baseline Scan (JSON report)
        run: |
          echo "Starting ZAP scan"
          docker run --rm --network="host" \
            -v ${{ github.workspace }}:/zap/wrk/:rw \
            ghcr.io/zaproxy/zap-stable:latest zap-baseline.py \
            -t http://localhost:8081 \
            -J zap-report.json || true

      - name: Convert ZAP JSON report to SARIF
        run: |
          python3 <<'EOF'
          import json

          def convert_zap_json_to_sarif(zap_json_path, sarif_path):
              with open(zap_json_path, 'r') as f:
                  zap_data = json.load(f)

              sarif = {
                  "version": "2.1.0",
                  "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
                  "runs": [{
                      "tool": {
                          "driver": {
                              "name": "OWASP ZAP",
                              "informationUri": "https://www.zaproxy.org/",
                              "rules": []
                          }
                      },
                      "results": []
                  }]
              }

              rules = {}
              results = []

              for alert in zap_data.get("alerts", []):
                  rule_id = alert.get("alertId", alert.get("alert", "Unknown"))
                  if rule_id not in rules:
                      rules[rule_id] = {
                          "id": rule_id,
                          "name": alert.get("alert", ""),
                          "shortDescription": {"text": alert.get("alert", "")},
                          "helpUri": alert.get("reference", ""),
                          "properties": {"tags": ["security", "zap"]}
                      }
                  for instance in alert.get("instances", []):
                      location = {
                          "physicalLocation": {
                              "artifactLocation": {
                                  "uri": instance.get("uri", "")
                              },
                              "region": {
                                  "startLine": 1
                              }
                          }
                      }
                      result = {
                          "ruleId": rule_id,
                          "message": {"text": alert.get("description", "")},
                          "locations": [location],
                          "level": "warning"
                      }
                      results.append(result)

              sarif["runs"][0]["tool"]["driver"]["rules"] = list(rules.values())
              sarif["runs"][0]["results"] = results

              with open(sarif_path, 'w') as f:
                  json.dump(sarif, f, indent=2)

          convert_zap_json_to_sarif('zap-report.json', 'zap-report.sarif')
          EOF

      - name: Upload ZAP SARIF results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: zap-report.sarif
          wait-for-processing: true

      - name: Upload ZAP SARIF as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-sarif-report
          path: zap-report.sarif
          retention-days: 5
