name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build vulnerable-api Docker image
        run: docker build -t vulnerable-api-practika:latest .

      - name: Create docker network
        run: |
          docker network create zap-net || true

      - name: Run vulnerable-api container
        run: |
          docker run -d --name vulnerable-api --network zap-net -p 8081:8081 vulnerable-api-practika:latest

      - name: Wait for vulnerable-api service to start
        run: |
          for i in {1..20}; do
            if curl --silent --fail http://localhost:8081; then
              echo "Service is up!"
              exit 0
            fi
            echo "Waiting for service..."
            sleep 5
          done
          echo "Service did not start in time"
          exit 1

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --rm --network zap-net -v ${{ github.workspace }}:/zap/wrk/:rw ghcr.io/zaproxy/zap2docker-stable zap-baseline.py \
            -t http://vulnerable-api:8081 \
            -J zap-report.json

      # Конвертация и загрузка SARIF тут (можно вставить твой Python скрипт и шаг upload-sarif)
      
      - name: Stop vulnerable-api container
        run: docker stop vulnerable-api
